version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/myApp
hooks:
  BeforeInstall:
    - location: CI-CD/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: CI-CD/after_install.sh
      timeout: 300
      runas: ec2-user 
  ApplicationStart:
    - location: CI-CD/application_start.sh
      timeout: 300
      runas: ec2-user
